// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC-MtrHdkjdrZUg9MG-Zl6OfjiDjJTM3w',
    appId: '1:297220299582:web:91d1f72b02ee78f19eea6f',
    messagingSenderId: '297220299582',
    projectId: 'projeto-livros-80dc9',
    authDomain: 'projeto-livros-80dc9.firebaseapp.com',
    storageBucket: 'projeto-livros-80dc9.firebasestorage.app',
    measurementId: 'G-ZBC4JTY8VX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArEBbaxasr6dJ6EuDevMILycTKog1FOoY',
    appId: '1:297220299582:android:e22a2ae11bf1941e9eea6f',
    messagingSenderId: '297220299582',
    projectId: 'projeto-livros-80dc9',
    storageBucket: 'projeto-livros-80dc9.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDC-MtrHdkjdrZUg9MG-Zl6OfjiDjJTM3w',
    appId: '1:297220299582:web:bd8d75834c806a309eea6f',
    messagingSenderId: '297220299582',
    projectId: 'projeto-livros-80dc9',
    authDomain: 'projeto-livros-80dc9.firebaseapp.com',
    storageBucket: 'projeto-livros-80dc9.firebasestorage.app',
    measurementId: 'G-2PMS28N0W2',
  );

}